<?php

namespace INTERMediator\FileMakerServer\RESTAPI\PersistentSession;

use INTERMediator\FileMakerServer\RESTAPI\FMDataAPI;
use RuntimeException;

/**
 * Class PersistentSession is the wrapper of persistent sessions.
 * The object of this class is going to be generated by the FMDataAPI class,
 * and you shouldn't call the constructor of this class.
 *
 * @package INTER-Mediator\FileMakerServer\RESTAPI\PersistentSession
 * @link https://github.com/msyk/FMDataAPI GitHub Repository
 * @version 36
 */
class PersistentSession
{
    /**
     * @var int
     * @ignore
     */
    private const TOKEN_TTL = 840;

    /**
     * @var SessionCacheInterface Cache backend for persistent sessions.
     * @ignore
     */
    private SessionCacheInterface $cache;
    /**
     * @var string Database name.
     * @ignore
     */
    private string $database;
    /**
     * @var string User name.
     * @ignore
     */
    private string $user;

    /**
     * @param SessionCacheInterface $cache
     * @param string $database Database name.
     * @param string $user User name.
     */
    public function __construct(
        SessionCacheInterface $cache,
        string                $database,
        string                $user)
    {
        $this->cache = $cache;
        $this->database = $database;
        $this->user = $user;
    }

    /**
     * Apply the cached session token to the FMDataAPI object if it exists.
     *
     * @param FMDataAPI $client The FMDataAPI object.
     * @return bool True if the cached session token was applied.
     */
    public function applyCachedSessionToken(FMDataAPI $client): bool
    {
        $token = $this->getCachedSessionToken();
        if ($token === false) {
            return false;
        }
        $client->setSessionToken($token);
        return true;
    }

    /**
     * Cache the current session token.
     *
     * @param FMDataAPI $client The FMDataAPI object.
     */
    public function cacheCurrentSessionToken(FMDataAPI $client): void
    {
        $token = $this->getCurrentSessionTokenOrFail($client);
        $this->cache->set($this->cacheKey(), $token, self::TOKEN_TTL);
    }

    /**
     * Clear the cached session token.
     */
    public function clearCachedSessionToken(): void
    {
        $this->cache->delete($this->cacheKey());
    }

    /**
     * Retrieve a cached token. Returns false if the key doesn't exist.
     * @return string|false
     */
    private function getCachedSessionToken(): string|false
    {
        return $this->cache->get($this->cacheKey());
    }

    /**
     * @param FMDataAPI $client
     * @return string
     */
    private function getCurrentSessionTokenOrFail(FMDataAPI $client): string
    {
        $token = $client->getSessionToken();
        if ($token === null) {
            throw new RuntimeException("Current session token is not available.");
        }
        return $token;
    }

    /**
     * @return string
     */
    private function cacheKey(): string
    {
        return "fm_token:{$this->database}:{$this->user}";
    }
}
