name: Setup PHP

inputs:
  php-version:
    description: 'PHP version to setup'
    required: false
    default: '8.5'
  extensions:
    description: 'Comma-separated list of PHP extensions to install'
    required: false
    default: 'mbstring, json, bcmath, zip, pdo, pdo_mysql, pdo_pgsql, pdo_sqlite, exif, gd, ldap, fileinfo'
  tools:
    description: 'Comma-separated list of tools to install'
    required: false
    default: composer:2.10.3, phan:6.0.5

runs:
  using: "composite"
  steps:
    - name: Setup PHP
      uses: shivammathur/setup-php@bc12f5cef4c73a871331e196ff380d38232ba293 # v2.40.0-beta
      with:
        php-version: ${{ inputs.php-version }}
        coverage: none
        extensions: ${{ inputs.extensions }}
        tools: ${{ inputs.tools }}

    - name: Setup Takumi Guard
      uses: flatt-security/setup-takumi-guard-packagist@bed25614416656a553e0a5d2bd379be72adcfd4f # v1.1.0
