name: Setup PHP

inputs:
  php-version:
    description: 'PHP version to setup'
    required: false
    default: '8.5'
  extensions:
    description: 'Comma-separated list of PHP extensions to install'
    required: false
    default: 'mbstring, json, bcmath, zip, pdo, pdo_mysql, pdo_pgsql, pdo_sqlite, exif, gd, ldap, fileinfo'
  tools:
    description: 'Comma-separated list of tools to install'
    required: false
    default: composer:2.10.0, phan:6.0.5

runs:
  using: "composite"
  steps:
    - name: Setup PHP
      uses: shivammathur/setup-php@f3e473d116dcccaddc5834248c87452386958240 # v2.37.2
      with:
        php-version: ${{ inputs.php-version }}
        coverage: none
        extensions: ${{ inputs.extensions }}
        tools: ${{ inputs.tools }}
