name: Mago

permissions:
  contents: read

on:
  push:
  pull_request:

jobs:
  run:
    name: Run Mago
    runs-on: 'ubuntu-latest'
    steps:
      - name: Checkout code
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: Setup PHP
        uses: ./.github/actions/setup-php

      - name: Install Mago
        run: composer config --no-plugins allow-plugins.carthage-software/mago true; composer require --dev carthage-software/mago:1.42.0

      - name: Run Mago
        run: ./vendor/bin/mago --config .mago/mago.toml analyze
