name: Psalm

permissions:
  contents: read

on:
  push:
  pull_request:

jobs:
  run:
    name: Run Psalm
    runs-on: 'ubuntu-latest'
    steps:
      - name: Checkout code
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: Setup PHP
        uses: ./.github/actions/setup-php

#      - name: Install Psalm
#        run: composer require --dev vimeo/psalm:6.16.1

      - name: Install dependencies
        run: composer update

      - name: Run Psalm
        run: ./vendor/bin/psalm --no-cache
